import {json,method,readBody,sameOrigin} from '../_lib/http.js';
import {authenticated,ensureAdminEnv,adminHeaders,responseMessage} from '../_lib/supabase.js';
import {validLine,calculate,getProduct,PIX_MAX_CENTS,CART_MAX_LINES} from '../_lib/catalog.js';
import {normalizeShipping,validShipping,orderId} from '../_lib/order.js';
function missingDb(msg){const s=String(msg).toLowerCase();return s.includes('does not exist')||s.includes('could not find the table')||s.includes('schema cache')||(s.includes('relation')&&s.includes('not')&&s.includes('exist'));}
function metaString(obj,keys){for(const k of keys){const v=obj?.[k];if(typeof v==='string'&&v.trim())return v.trim()}return null;}
export default async function handler(req,res){if(req.method!=='POST')return method(res,['POST']);if(!sameOrigin(req))return json(res,403,{error:'Origem da requisição não permitida.'});try{
  const admin=ensureAdminEnv();const {user}=await authenticated(req,res);if(!user?.id)return json(res,401,{error:'Faça login para continuar.'});
  const b=await readBody(req);const key=typeof b.idempotencyKey==='string'?b.idempotencyKey.trim():'';const rawLines=Array.isArray(b.lines)?b.lines:[];const shipping=normalizeShipping(b.shipping);
  if(b.acceptTerms!==true||key.length<16||key.length>96||rawLines.length<1||rawLines.length>CART_MAX_LINES||!rawLines.every(validLine)||!validShipping(shipping))return json(res,400,{error:'Revise os itens, o endereço e a confirmação das políticas.'});
  const uniqueKeys=rawLines.map(x=>`${x.productId}:${x.variant}`);if(new Set(uniqueKeys).size!==uniqueKeys.length)return json(res,400,{error:'O mesmo produto não pode aparecer duplicado no pedido.'});
  const total=calculate(rawLines);if(total<=0)return json(res,400,{error:'Carrinho inválido.'});if(total>PIX_MAX_CENTS)return json(res,422,{error:'Revise os itens do carrinho antes de continuar com o pagamento.'});
  const now=new Date().toISOString();const email=typeof user.email==='string'?user.email:null;const name=metaString(user.user_metadata,['name','full_name','display_name'])||(email?email.split('@')[0]:'Cliente');
  const up=await fetch(`${admin.url}/rest/v1/users?on_conflict=openId`,{method:'POST',headers:adminHeaders(admin.secretKey,'resolution=merge-duplicates,return=representation'),body:JSON.stringify({openId:user.id,name,email,loginMethod:metaString(user.app_metadata,['provider'])||'email',lastSignedIn:now,updatedAt:now}),cache:'no-store'});
  if(!up.ok){const d=await responseMessage(up);return json(res,missingDb(d)?412:500,{error:missingDb(d)?'Execute o arquivo supabase/schema.sql no SQL Editor do Supabase.':`Não foi possível sincronizar o cliente: ${d}`});}
  let users=await up.json().catch(()=>[]);let userId=Number(users?.[0]?.id||0);if(!userId){const ur=await fetch(`${admin.url}/rest/v1/users?select=id&openId=eq.${encodeURIComponent(user.id)}&limit=1`,{headers:adminHeaders(admin.secretKey),cache:'no-store'});users=await ur.json().catch(()=>[]);userId=Number(users?.[0]?.id||0);}if(!userId)return json(res,500,{error:'Não foi possível identificar o cliente no banco.'});
  const ex=await fetch(`${admin.url}/rest/v1/orders?select=id,status,totalCents,userId,providerReference,createdAt&idempotencyKey=eq.${encodeURIComponent(key)}&limit=1`,{headers:adminHeaders(admin.secretKey),cache:'no-store'});if(!ex.ok){const d=await responseMessage(ex);return json(res,missingDb(d)?412:500,{error:missingDb(d)?'Execute o arquivo supabase/schema.sql no SQL Editor do Supabase.':d});}const rows=await ex.json().catch(()=>[]);if(rows[0]){if(Number(rows[0].userId)!==userId)return json(res,409,{error:'Chave de pedido inválida.'});return json(res,200,{orderId:rows[0].id,status:rows[0].status,total:rows[0].totalCents,hasPayment:Boolean(rows[0].providerReference),message:'Pedido já existente; nenhum duplicado foi criado.'});}
  const id=orderId();const cr=await fetch(`${admin.url}/rest/v1/orders`,{method:'POST',headers:adminHeaders(admin.secretKey,'return=minimal'),body:JSON.stringify({id,userId,totalCents:total,status:'pending',idempotencyKey:key}),cache:'no-store'});if(!cr.ok){const d=await responseMessage(cr);return json(res,missingDb(d)?412:500,{error:missingDb(d)?'Execute o arquivo supabase/schema.sql no SQL Editor do Supabase.':`Não foi possível criar o pedido: ${d}`});}
  const itemPayload=rawLines.map(l=>{const p=getProduct(l.productId);return {orderId:id,productId:p.id,variant:l.variant,quantity:l.quantity,unitPriceCents:p.promotionalPriceCents};});
  const items=await fetch(`${admin.url}/rest/v1/order_items`,{method:'POST',headers:adminHeaders(admin.secretKey,'return=minimal'),body:JSON.stringify(itemPayload),cache:'no-store'});
  const ship=await fetch(`${admin.url}/rest/v1/order_shipping`,{method:'POST',headers:adminHeaders(admin.secretKey,'return=minimal'),body:JSON.stringify({orderId:id,...shipping}),cache:'no-store'});
  if(!items.ok||!ship.ok){const d=!items.ok?await responseMessage(items):await responseMessage(ship);await fetch(`${admin.url}/rest/v1/orders?id=eq.${encodeURIComponent(id)}`,{method:'DELETE',headers:adminHeaders(admin.secretKey,'return=minimal'),cache:'no-store'}).catch(()=>{});return json(res,missingDb(d)?412:500,{error:missingDb(d)?'Execute supabase/catalog-migration.sql e depois supabase/schema.sql no SQL Editor do Supabase.':`Não foi possível salvar todos os dados do pedido: ${d}`});}
  return json(res,201,{orderId:id,status:'pending',total,message:'Pedido criado com sucesso.'});
}catch(e){console.error('[orders/create]',e);return json(res,500,{error:e instanceof Error?e.message:'Não foi possível criar o pedido.'});}}
